### ISSUE TITLE
大哥请教的一个充值回调的问题

### ISSUE THREAD

**Issue by bournes** [zhangqi-ulua/ServerFramework#56]
客户端发送充值到苹果商店，后端要提供一个苹果商店的回调地址。。

我该如何设计呢？ 

GM提供了一个GATEWAY的链接。。。我是不是也需要从GM上提供一条链接呢？？还是不需要这样子做？？

请教大哥给指条明路？？万谢！！

**Comment by zhangqi-ulua** [comment]
如果是我来做的话，我会把充值单独拆成一个独立的服务器，然后与GM交互
