### ISSUE TITLE
打开.bat文件的时候就出问题了。。

### ISSUE THREAD

**Issue by chenzhuo137** [zhangqi-ulua/ServerFramework#8]
C:\Users\Administrator\IdeaProjects\ServerFramework-master\trunk\tools\release\AutoBuildServer>build.bat
'僭诵?' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'n' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'定后按任意键继续' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'r' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'/Q' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'务器' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'cServer' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'ackage' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'battleServer' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'\..\' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'ho' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
请按任意键继续. . .

**Comment by zhangqi-ulua** [comment]
明显是你自己改动了文件编码，导致windows识别为乱码

**Comment by zhangqi-ulua** [comment]
解决了吧应该？BAT编码必须是windows默认的，而不能是UTF-8之类的，否则windows下是乱码

**Comment by chenzhuo137** [comment]
...重新解压之后再点也还是不行

**Comment by zhangqi-ulua** [comment]
> ...重新解压之后再点也还是不行

解压？你不是clone这个git，而是直接用github下载的zip？建议clone再试下。我只知道github如果是下载zip包，txt好像换行会不正常。我也都是clone的，没有问题

**Comment by chenzhuo137** [comment]
用git clone可以执行，但是有报错，应该是maven的错误

**Comment by chenzhuo137** [comment]
用git clone后.bat文件可以执行，但是会报错，应该是maven的问题，我用的是idea自带的maven3.6.1

[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
'cmd' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by chenzhuo137** [comment]
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project gateway: Compilation failure: Compilation failure:
[ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/redis/serializer/IntegerRedisSerializer.java:[7,8] 类重复: org.zhangqi.redis.serializer.IntegerRedisSerializer
[ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/utils/DateTimeUtil.java:[12,8] 类重复: org.zhangqi.utils.DateTimeUtil
[ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/actor/ResponseActor.java:[13,8] 类重复: org.zhangqi.actor.ResponseActor
[ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/msg/serializer/RemoteMessageSerializer.java:[12,8] 类重复: org.zhangqi.msg.serializer.RemoteMessageSerializer
[ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/redis/serializer/ByteRedisSerializer.java:[8,8] 类重复: org.zhangqi.redis.serializer.ByteRedisSerializer
[ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/manager/MessageManager.java:[19,8] 类重复: org.zhangqi.manager.MessageManager
[ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/manager/ConfigManager.java:[9,8] 类重复: org.zhangqi.manager.ConfigManager
[ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/dao/UserDAO.java:[13,8] 类重复: org.zhangqi.dao.UserDAO
[ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/manager/IManager.java:[3,8] 类重复: org.zhangqi.manager.IManager
[ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/network/Netty4ProtocolCodecFactory.java:[15,8] 类重复: org.zhangqi.network.Netty4ProtocolCodecFactory
[ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/network/WebSocketFrameHandler.java:[29,8] 类 重复: org.zhangqi.network.WebSocketFrameHandler
[ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/Main.java:[10,8] 类重复: org.zhangqi.Main
[ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/dao/LoadBalanceDAO.java:[19,8] 类重复: org.zhangqi.dao.LoadBalanceDAO
[ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/msg/serializer/NetMessageSerializer.java:[12,8] 类重复: org.zhangqi.msg.serializer.NetMessageSerializer
[ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/manager/SpringManager.java:[9,8] 类重复: org.zhangqi.manager.SpringManager
[ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/proto/Rpc.java:[6,14] 类重复: org.zhangqi.proto.Rpc
[ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/utils/StringUtil.java:[5,8] 类重复: org.zhangqi.utils.StringUtil
[ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/actor/GatewayActor.java:[37,8] 类重复: org.zhangqi.actor.GatewayActor
[ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/manager/NettyManager.java:[15,8] 类重复: org.zhangqi.manager.NettyManager
[ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/actor/ChannelActor.java:[24,8] 类重复: org.zhangqi.actor.ChannelActor
[ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/proto/Common.java:[6,14] 类重复: org.zhangqi.proto.Common
[ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/redis/serializer/CommonRedisSerializer.java:[9,8] 类重复: org.zhangqi.redis.serializer.CommonRedisSerializer
[ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/msg/LocalMessage.java:[5,8] 类重复: org.zhangqi.msg.LocalMessage
[ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/proto/LocalServer.java:[6,14] 类重复: org.zhangqi.proto.LocalServer
[ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/manager/CoreManager.java:[6,8] 类重复: org.zhangqi.manager.CoreManager
[ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/service/LoadBalanceService.java:[10,8] 类重复: org.zhangqi.service.LoadBalanceService
[ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/msg/AbstractMessage.java:[5,17] 类重复: org.zhangqi.msg.AbstractMessage
[ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/utils/ClassScanerUtil.java:[30,8] 类重复: org.zhangqi.utils.ClassScanerUtil
[ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/msg/NetResponseMessage.java:[3,8] 类重复: org.zhangqi.msg.NetResponseMessage
[ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/constants/GlobalConstant.java:[3,8] 类重复: org.zhangqi.constants.GlobalConstant
[ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/utils/MD5Util.java:[10,8] 类重复: org.zhangqi.utils.MD5Util
[ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/msg/NetMessage.java:[20,8] 类重复: org.zhangqi.msg.NetMessage
[ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/msg/IMessage.java:[5,8] 类重复: org.zhangqi.msg.IMessage
[ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/proto/RemoteServer.java:[6,14] 类重复: org.zhangqi.proto.RemoteServer
[ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/service/UserService.java:[18,8] 类重复: org.zhangqi.service.UserService
[ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/redis/serializer/LongRedisSerializer.java:[7,8] 类重复: org.zhangqi.redis.serializer.LongRedisSerializer
[ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/constants/RedisKeyHelper.java:[5,8] 类重复: org.zhangqi.constants.RedisKeyHelper
[ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/msg/RemoteMessage.java:[16,8] 类重复: org.zhangqi.msg.RemoteMessage
[ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/constants/SystemConfigKeyConstant.java:[3,8] 类重复: org.zhangqi.constants.SystemConfigKeyConstant
[ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/constants/RedisKeyConstant.java:[3,8] 类重复: org.zhangqi.constants.RedisKeyConstant
[ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/manager/OnlineClientManager.java:[16,8] 类重 复: org.zhangqi.manager.OnlineClientManager
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
'cmd' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by zhangqi-ulua** [comment]
> Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project gateway: Compilation failure: Compilation failure:
> [ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/redis/serializer/IntegerRedisSerializer.java:[7,8] 类重复: org.zhangqi.redis.serializer.IntegerRedisSerializer
> [ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/utils/DateTimeUtil.java:[12,8] 类重复: org.zhangqi.utils.DateTimeUtil
> [ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/actor/ResponseActor.java:[13,8] 类重复: org.zhangqi.actor.ResponseActor
> [ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/msg/serializer/RemoteMessageSerializer.java:[12,8] 类重复: org.zhangqi.msg.serializer.RemoteMessageSerializer
> [ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/redis/serializer/ByteRedisSerializer.java:[8,8] 类重复: org.zhangqi.redis.serializer.ByteRedisSerializer
> [ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/manager/MessageManager.java:[19,8] 类重复: org.zhangqi.manager.MessageManager
> [ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/manager/ConfigManager.java:[9,8] 类重复: org.zhangqi.manager.ConfigManager
> [ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/dao/UserDAO.java:[13,8] 类重复: org.zhangqi.dao.UserDAO
> [ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/manager/IManager.java:[3,8] 类重复: org.zhangqi.manager.IManager
> [ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/network/Netty4ProtocolCodecFactory.java:[15,8] 类重复: org.zhangqi.network.Netty4ProtocolCodecFactory
> [ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/network/WebSocketFrameHandler.java:[29,8] 类 重复: org.zhangqi.network.WebSocketFrameHandler
> [ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/Main.java:[10,8] 类重复: org.zhangqi.Main
> [ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/dao/LoadBalanceDAO.java:[19,8] 类重复: org.zhangqi.dao.LoadBalanceDAO
> [ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/msg/serializer/NetMessageSerializer.java:[12,8] 类重复: org.zhangqi.msg.serializer.NetMessageSerializer
> [ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/manager/SpringManager.java:[9,8] 类重复: org.zhangqi.manager.SpringManager
> [ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/proto/Rpc.java:[6,14] 类重复: org.zhangqi.proto.Rpc
> [ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/utils/StringUtil.java:[5,8] 类重复: org.zhangqi.utils.StringUtil
> [ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/actor/GatewayActor.java:[37,8] 类重复: org.zhangqi.actor.GatewayActor
> [ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/manager/NettyManager.java:[15,8] 类重复: org.zhangqi.manager.NettyManager
> [ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/actor/ChannelActor.java:[24,8] 类重复: org.zhangqi.actor.ChannelActor
> [ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/proto/Common.java:[6,14] 类重复: org.zhangqi.proto.Common
> [ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/redis/serializer/CommonRedisSerializer.java:[9,8] 类重复: org.zhangqi.redis.serializer.CommonRedisSerializer
> [ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/msg/LocalMessage.java:[5,8] 类重复: org.zhangqi.msg.LocalMessage
> [ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/proto/LocalServer.java:[6,14] 类重复: org.zhangqi.proto.LocalServer
> [ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/manager/CoreManager.java:[6,8] 类重复: org.zhangqi.manager.CoreManager
> [ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/service/LoadBalanceService.java:[10,8] 类重复: org.zhangqi.service.LoadBalanceService
> [ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/msg/AbstractMessage.java:[5,17] 类重复: org.zhangqi.msg.AbstractMessage
> [ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/utils/ClassScanerUtil.java:[30,8] 类重复: org.zhangqi.utils.ClassScanerUtil
> [ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/msg/NetResponseMessage.java:[3,8] 类重复: org.zhangqi.msg.NetResponseMessage
> [ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/constants/GlobalConstant.java:[3,8] 类重复: org.zhangqi.constants.GlobalConstant
> [ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/utils/MD5Util.java:[10,8] 类重复: org.zhangqi.utils.MD5Util
> [ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/msg/NetMessage.java:[20,8] 类重复: org.zhangqi.msg.NetMessage
> [ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/msg/IMessage.java:[5,8] 类重复: org.zhangqi.msg.IMessage
> [ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/proto/RemoteServer.java:[6,14] 类重复: org.zhangqi.proto.RemoteServer
> [ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/service/UserService.java:[18,8] 类重复: org.zhangqi.service.UserService
> [ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/redis/serializer/LongRedisSerializer.java:[7,8] 类重复: org.zhangqi.redis.serializer.LongRedisSerializer
> [ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/constants/RedisKeyHelper.java:[5,8] 类重复: org.zhangqi.constants.RedisKeyHelper
> [ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/msg/RemoteMessage.java:[16,8] 类重复: org.zhangqi.msg.RemoteMessage
> [ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/constants/SystemConfigKeyConstant.java:[3,8] 类重复: org.zhangqi.constants.SystemConfigKeyConstant
> [ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/constants/RedisKeyConstant.java:[3,8] 类重复: org.zhangqi.constants.RedisKeyConstant
> [ERROR] /F:/github/ServerFramework/trunk/gateway/src/main/java/org/zhangqi/manager/OnlineClientManager.java:[16,8] 类重 复: org.zhangqi.manager.OnlineClientManager
> [ERROR] -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
> 'cmd' 不是内部或外部命令，也不是可运行的程序
> 或批处理文件。

是用jdk8么？还是其他的

**Comment by chenzhuo137** [comment]
用的jdk8

**Comment by zhangqi-ulua** [comment]
> 用的jdk8

这个我不太清楚了。我是官网下载的独立的maven，eclipse也是引用独立的maven

搜了个，不知对你是否有帮助
https://www.cnblogs.com/chuijingjing/p/10522145.html

**Comment by chenzhuo137** [comment]
恩恩，谢谢大佬

**Comment by zhangqi-ulua** [comment]
> 恩恩，谢谢大佬

客气了。加一下QQ交流群吧132108644。如果还不行，在帮你看看

**Comment by chenzhuo137** [comment]
恩恩，好的，我就在群里，默默潜水哈哈哈哈
