### ISSUE TITLE
GM服务器能做分布式负载均衡吗？

### ISSUE THREAD

**Issue by bournes** [zhangqi-ulua/ServerFramework#9]
GM服务器对外开放一个HTTP获取地址！如果这个地址被用户拉垮了呢！！！
GM服务器能做负载均衡吗？

**Comment by zhangqi-ulua** [comment]
如果担心这个问题，我建议可以单独将这个功能用springboot简单写个服务器，可以有多台去接收用户获取一个gateway的请求然后返回。GM服务器本身的功能就只有类似服务发现、GM操作，没什么压力，到真没必要也做多台
